
import type { Layout16ModuleConfig } from './types';
import { FileText, Users, Sparkles } from 'lucide-react';
import { 
  BurgerMenu,
  ChartLineStar,
  Element7,
  Element12,
  ElementEqual,
  Document,
  Folder,
  Frame,
  GamerCards,
  GamerStars,
  Grid,
  Home,
  MessageText2,
  Messages,
  NotificationStatus,
  Pencil,
  Plus,
  Rocket,
  Save2,
  Setting2,
  StatusOnline,
  TabletTextDown,
  Technology4,
  TextCircle,
  Up, } from '@/components/icons';
export const CMS_MODULE: Layout16ModuleConfig = {
  id: 'cms',
  title: 'CMS',
  tooltip: 'CMS',
  icon: Document,
  path: '/layout-16/modules/cms',
  rootPath: '/layout-16/modules/cms',
  enabled: true,
  secondaryItems: [
    {
      id: 'Pages',
      title: 'Pages',
      path: '/cms/pages/list',
      section: 'primary',
      icon: Document,
      enabled: true,
    },
    {
      id: 'cms-2',
      title: 'CMS2',
      path: '#',
      section: 'primary',
      icon: Folder,
      enabled: true,
    },
    {
      id: 'cms-3',
      title: 'CMS3',
      path: '#',
      section: 'primary',
      icon: Sparkles,
      enabled: false,
    },
    {
      id: 'cms-ws-1',
      title: 'CMS Workspace',
      path: '#',
      section: 'workspaces',
      icon: Folder,
      enabled: true,
    },
    {
      id: 'cms-com-1',
      title: 'CMS Community',
      path: '#',
      section: 'communities',
      icon: Users,
      enabled: true,
    },
    {
      id: 'cms-res-1',
      title: 'CMS Resource',
      path: '#',
      section: 'resources',
      icon: Sparkles,
      enabled: true,
      badge: 'New',
    },
  ],
};
